apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: llkyn853x-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/llkyn853x-java-quarkus-gitops